stages:
  - build
  - image
  - image-tag
  - deploy

# template jobs

.branch-deploy: &branch-deploy
  only:
    - master

.build-docker: &build-docker
  image: docker
  services:
    - docker:dind
  tags:
    - runner:k8s
    - cloud:aws

  before_script:
    # prep secrets
    - mkdir /root/.docker
    - ln -s /secrets/docker /root/.docker/config.json
    - docker info
  variables: &vars-docker
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    IMAGE_TAG: ssube/isolex:$CI_COMMIT_REF_SLUG

.build-retag: &build-retag
  stage: image-tag
  script:
    - docker pull ${IMAGE_SRC}
    - docker tag ${IMAGE_SRC} ${IMAGE_DST}
    - docker push ${IMAGE_DST}

# build jobs
build-node:
  image: apextoaster/node:master
  stage: build
  tags:
    - runner:k8s

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - yarn
    - make strict

  artifacts:
    expire_in: 1 week
    paths:
      - out/coverage
      - out/docs
      - out/main-bundle.*
      - out/version.json

build-image:
  <<: [*build-docker]
  stage: image

  dependencies:
    - build-node
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# tag releases
tag-latest:
  <<: [*branch-deploy, *build-docker, *build-retag]

  dependencies: []
  variables:
    <<: *vars-docker
    IMAGE_SRC: ssube/isolex:$CI_COMMIT_REF_SLUG
    IMAGE_DST: ssube/isolex:latest

tag-version:
  <<: [*build-docker, *build-retag]
  only:
    - tags

  dependencies: []
  variables:
    <<: *vars-docker
    IMAGE_SRC: ssube/isolex:latest
    IMAGE_DST: ssube/isolex:${CI_COMMIT_TAG}

# deploy master
deploy-bot:
  <<: [*branch-deploy]
  stage: deploy
  image: apextoaster/kube:1.9
  tags:
    - runner:k8s
    - cloud:ovh

  dependencies: []
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-isolex
  script:
    - kubectl describe deployment isolex --namespace=isolex
    - kubectl delete pod $(kubectl get pods --namespace=isolex | tail -n 1 | awk '{ print $1; }') --namespace=isolex